apiVersion: v1
kind: Service
metadata:
  name: langflow-postgres
  namespace: essedum
  labels:
    app: langflow-postgres
spec:
  selector:
    app: langflow-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
