apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.deploymentName }}
  labels:
    app: mysql
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          args:
            - "--datadir={{ .Values.mysql.dataDir }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword | quote }}
          ports:
            - containerPort: {{ .Values.mysql.containerPort }}
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: {{ .Values.mysql.mountPath }}
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.pvc.name }}
