apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: leap-app-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  type: LoadBalancer
