apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: {{ .Values.keycloak.httpsPort }}
      targetPort: {{ .Values.keycloak.httpsPort }}
  type: LoadBalancer