apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: {{ .Values.keycloak.httpsPort }}
      targetPort: {{ .Values.keycloak.httpsPort }}
  type: LoadBalancer
