apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: essedum
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: essedum-1
      containers:
        - name: backend
          image: essedum/backend:latest
          imagePullPolicy: Never
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: http
          envFrom:
            - configMapRef:
                name: essedum-config
            - secretRef:
                name: essedum-secret
          env:
            - name: LEAP_HOME
              value: "/app"
            - name: spring.config.location
              value: "/app/conf/"
            - name: encryption.key
              valueFrom:
                secretKeyRef:
                  name: essedum-secret
                  key: ENCRYPTION_KEY
            - name: encryption.salt
              valueFrom:
                secretKeyRef:
                  name: essedum-secret
                  key: ENCRYPTION_SALT
            - name: LOG_PATH
              value: "/app/log"
            - name: license
              valueFrom:
                secretKeyRef:
                  name: essedum-secret
                  key: LICENSE
            - name: publickey
              valueFrom:
                secretKeyRef:
                  name: essedum-secret
                  key: PUBLIC_KEY
            - name: logging.level.com.springframework.security
              value: "DEBUG"
            - name: logging.level.com.infosys.icets.ai.comm.lib.util.logger
              value: "ERROR"
            - name: spring.profiles.active
              value: "mysql,dbjwt,btf,dbconstants,vault,github"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - "echo > /dev/tcp/127.0.0.1/8082"
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - "echo > /dev/tcp/127.0.0.1/8082"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
