apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: essedum
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
