apiVersion: v1
kind: Service
metadata:
  name: py-job-executor
  namespace: essedum
  labels:
    app: py-job-executor
spec:
  selector:
    app: py-job-executor
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
