export const Msg = {
 APP: "LEAP",
 RPT: "LEAP",
 INF001: "Widget saved successfully",
 INF002: "Widget updated successfully",
 INF003: "Widget deleted successfully",
 INF004: "Widget exported successfully",
 INF005: "Chart-config deleted",
 INF006: "View saved successfully",
 INF007: "View updated successfully",
 INF028: "View deleted successfully",
 INF008: "Dashboard saved successfully",
 INF009: "Dashboard updated successfully",
 INF010: "Dashboard deleted successfully ",
 INF011: "Layout updated successfully",
 INF012: "User saved successfully",
 INF013: "User deleted successfully",
 INF014: "User updated successfully",
 INF015: "User not found",
 INF016: "No columns defined for selected record type",
 INF017: "Data uploaded successfully in DB",
 INF018: "No Data to Upload",
 INF019: "Enter all mandatory fields",
 INF020: "Enter metadata",
 INF021: "Saved record type and metadata",
 INF022: "Saved OK and msg emitted",
 INF023: "Saved OK",
 INF024: "Updated OK and msg emitted",
 INF025: "Updated OK",
 INF026: "Cancel clicked and msg emitted",
 INF027: "Deleted OK",
 INF029: "No data service found for the selected Record type",

 ERR001: "Color type as threshold can be chosen only once for a combo chart",
 ERR002: "Enter all threshold values",
 ERR003: "Threshold lower limit should be lesser than Upper limit",
 ERR004: "Widget cannot be created",
 ERR005: "Chart-config cannot be deleted",
 ERR006: "Lower limit should be lesser than Upper limit",
 ERR007: "Duplicate dashboard name",
 ERR008: "Server Error",
 ERR009: "Could not fetch dashboards",
 ERR010: "Dashboard cannot be deleted",
 ERR011: "Widget cannot be deleted",
 ERR012: "Could not get the results",
 ERR013: "Could not save",
 ERR014: "Could not update",
 ERR015: "Could not delete",
 ERR016: "License Expired",
 ERR017: "Access Denied",
 ERR018: "ngOnInit error",
 ERR019: " already exists as ",
 ERR020: ". To add this user with another role, delete and add the user with the desired Role",
 ERR021: "User cannot be found",
 ERR022: "User cannot be deleted",
 ERR023: "All fields are mandatory",
 ERR024: "Please validate the csv header",
 ERR025: "Could not save the data",
 ERR026: "Record name already exists",
 ERR027: "Could not save record type",
 ERR028: "Incorrect csv header",
 ERR029: "could not fetch dashboard",
 ERR030: "Failed to delete",
 ERR031: "Couldn't fetch data!",
 ERR032: "LEAP best supported in chrome",
 ERR033: "No view assigned to user",
 ERR034: "Could not fetch views",
 ERR035: "View cannot be deleted",
};
