apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: essedum
  labels:
    app: buildkitd
spec:
  selector:
    app: buildkitd
  ports:
    - name: buildkit
      port: 1234
      targetPort: 1234
  type: ClusterIP
