s3proxy.authorization=none
s3proxy.endpoint=http://0.0.0.0:8081

s3proxy.identity=aiplatformstorageacc
s3proxy.credential=jQ4a3xF4UkrF2PQUooK9NKdiJe1Z9Qx08DhyYFaTOgF3Sl9rD6jo5Pdjz+v86TNdJvlsM5v9QCfU+AStb+OG7A==

s3proxy.cors-allow-all=true

jclouds.provider=azureblob
jclouds.identity=aiplatformstorageacc
jclouds.credential=jQ4a3xF4UkrF2PQUooK9NKdiJe1Z9Qx08DhyYFaTOgF3Sl9rD6jo5Pdjz+v86TNdJvlsM5v9QCfU+AStb+OG7A==

jclouds.azureblob.endpoint=https://aiplatformstorageacc.blob.core.windows.net