# GitHub OAuth Client Credentials
github.oauth.client-id=
github.oauth.client-secret=
github.oauth.redirect-uri=https://essedum-lfn.infosys.com/api/github/oauth/callback
github.oauth.scope=repo,user

# GitHub OAuth URLs
github.oauth.authorization-uri=https://github.com/login/oauth/authorize
github.oauth.token-uri=https://github.com/login/oauth/access_token

# GitHub SSL Configuration
github.ssl.verify=false