apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder-sa
  namespace: aipns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
  namespace: aipns
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create","get","list","watch","patch","update","delete"]   # adjust verbs to your needs


  - apiGroups: [""]
    resources: ["secrets","services"]
    verbs: ["get","list","watch","create","update","patch","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: aipns
subjects:
  - kind: ServiceAccount
    name: builder-sa
    namespace: aipns
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io