apiVersion: apps/v1
kind: Deployment
metadata:
  name: essedum-backend
  namespace: aipns # Namespace where the deployment will run
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: essedum-backend
  template:
    metadata:
      labels:
        app: essedum-backend
    spec:
      containers:
      - name: essedum-backend
        image: 10.200.111.174:5000/essedum_app_backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: essedum-backend-service
  namespace: aipns
spec:
  selector:
    app: essedum-backend # Matches the label in the Deployment
  ports:
  - protocol: TCP
    port: 8080          # External port to expose
    targetPort: 8082  # Port where the application is running inside the pod
  type: LoadBalancer
