apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: aipns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.3
          args:
            - "start-dev"
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_HTTP_PORT
              value: "8180"
            - name: KC_HTTPS_PORT
              value: "8443"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTPS_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: "aiplatform.az.ad.idemo-ppc.com"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/etc/keycloak/certs/tls.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/etc/keycloak/certs/tls.key"
          ports:
            - containerPort: 8443
              protocol: TCP

          volumeMounts:
            - name: tls-cert
              mountPath: /etc/keycloak/certs
              readOnly: true
      volumes:
        - name: tls-cert
          secret:
            secretName: aiplatform-secret


---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: aipns
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer
