apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlfile-pv
  namespace: aipns
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /mnt/mysql-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: aipns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: mysqlfile-pv
