apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrantfile-pv
  namespace: aipns
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /mnt/qdrant-data
    type: DirectoryOrCreate
