apiVersion: v1
kind: Service
metadata:
  name: py-job-sagemaker-executer
  namespace: essedum
  labels:
    app: py-job-sagemaker-executer
spec:
  selector:
    app: py-job-sagemaker-executer
  ports:
    - name: http
      port: 5002
      targetPort: 5002
  type: ClusterIP
