SET IDENTITY_INSERT cap_config ON
GO

insert  into cap_config(ConfigId,AppName,ConfigName,ConfigVal,ProjectId,IsEncrypt,InstanceName) values 
(1,'API','Frequency','5',NULL,0,NULL),
(2,'API','useSQL','False',NULL,0,NULL),
(3,'API','CollectionPrefix','cap',NULL,0,NULL),
(4,'API','UseUsmTables','True',NULL,0,NULL),
(5,'API','TakeScreenShots','RESOLVER,Standard',NULL,0,NULL),
(6,'API','TriggeredFromIAMP','true',NULL,0,NULL),
(7,'API','IncidentChartDefaultSetLast_N_Days','30',NULL,0,NULL),
(8,'API','HeatMapDataNdays','30',NULL,0,NULL),
(9,'API','ScriptFolderPath','\\placeholder',NULL,0,NULL),
(10,'API','DownloadFilePath','\\placeholder',NULL,0,NULL),
(11,'API','RelevantDownloadUrl','http://victadpst-07:3800/videoanomaly/',NULL,0,NULL),
(12,'API','LogFolderPath','',NULL,0,NULL),
(13,'API','LogToFile','False',NULL,0,NULL),
(14,'API','VAStatusTimer','3',NULL,0,NULL),
(15,'API','BlockedCategoryRetryCount','3',NULL,0,NULL),
(16,'API','IsAssetStoreIntegrated','False',NULL,0,NULL),
(17,'API','HashiCorpBaseUrl','http://localhost:8200/',NULL,0,NULL),
(18,'API','GamificationIntegration:IsIntegrated','False',NULL,0,NULL),
(19,'API','GamificationIntegration:ApplicationId','53183',NULL,0,NULL),
(20,'API','GamificationIntegration:TokenNo','2EU3Z576AA',NULL,0,NULL),
(21,'API','GamificationIntegration:API','http://localhost',NULL,0,NULL),
(22,'API','GamificationIntegration:CreatedActivityId','73766',NULL,0,NULL),
(23,'API','GamificationIntegration:ResolvedActivityId','73767',NULL,0,NULL),
(24,'API','GamificationIntegration:ReopenedActivityId','73768',NULL,0,NULL),
(25,'API','GamificationIntegration:AutoRegisterUser','True',NULL,0,NULL),
(26,'API','GamificationIntegration:AutoRegisterPortfolio','Acme',NULL,0,NULL),
(27,'API','GamificationIntegration:AutoRegisterRole','User',NULL,0,NULL),
(28,'API','GamificationIntegration:AutoRegisterUserPassword','ZTLiPW70rwTT/6VoFmw0zg==',NULL,0,NULL),
(29,'API','SendEmailNotification:SmtpServer','172.21.5.10',NULL,0,NULL),
(30,'API','SendEmailNotification:SmtpPort','25',NULL,0,NULL),
(31,'API','SendEmailNotification:FromEmailId','rahul.singhal01@lfn.com',NULL,0,NULL),
(32,'API','SendEmailNotification:EncryptedPsw','CE94Uypj+7U0dRvmPx7Tnw==',NULL,0,NULL),
(33,'API','SendEmailNotification:Subject',' ',NULL,0,NULL),
(34,'API','SendEmailNotification:Body',' ',NULL,0,NULL),
(35,'API','RewriteUrl','apicapi?query',NULL,0,NULL),
(36,'API','LoggingType','ERROR',NULL,0,NULL),
(37,'API','ConsecutiveTransactions','2',NULL,0,NULL),
(38,'API','SchedulerConfig','TRUE',NULL,0,NULL),
(39,'API','IsIAMPIntegrated','TRUE',NULL,0,NULL),
(40,'API','WorkflowBinarySettings:OldVersionsToKeep','3',NULL,0,NULL),
(41,'API','WorkflowBinarySettings:BackupBeforeDelete','True',NULL,0,NULL),
(42,'API','WorkflowBinarySettings:BackupPath','\\placeholder',NULL,0,NULL),
(43,'Generic','WebAPI','https://essedum2:3000/icapapi/',NULL,0,NULL),
(44,'Generic','ConnString','pIRxkRjjOQK9KGkb+PLfO3mqKf67BfhkfZBoWAeTGNouz3KNn1lhoAOpZYJunGndSsYJ2FG466WTwohdJ2ZGpv80fqhFW6gb7bIDMymHkGID/OTAmyut9CKMQ4Dbn6BbV2m6etGAe4U1EQcH2qmrzzO6DOVRlt5mbtPFSdzIWlovkYIhfVtPqNsE9prdGHXNvIOVYk2/RReU4BD3odXhxQ==',NULL,0,NULL),
(45,'Generic','UseSQLServer','False',NULL,0,NULL),
(46,'Generic','EnableAllLogs','True',NULL,0,NULL),
(47,'Generic','IECPUrl','http://localhost/',NULL,0,NULL),
(48,'Generic','TesseractWebAPIURL','http://localhost/',NULL,0,NULL),
(49,'Generic','EnableConsoleLogs','True',NULL,0,NULL),

(51,'Generic','CollectionPrefix','cap',NULL,0,NULL),
(52,'capagent','ProbeMonitoring','False',NULL,0,NULL),
(53,'capagent','ScreenshotValidity','30',NULL,0,NULL),

(55,'capagent','FileLog','True',NULL,0,NULL),

(57,'capagent','SleepTime','5000',NULL,0,NULL),
(58,'capagent','BotScreenShotMode','File',NULL,0,NULL),
(59,'capagent','BotScreenShotThresholdDays','7',NULL,0,NULL),

(61,'capworkflowexecution','WFCancelCheckTimeInSeconds','7',NULL,0,NULL),
(62,'capworkflowexecution','PassWFRunExeID','True',NULL,0,NULL),
(63,'capworkflowexecution','WorkflowParamName','Input',NULL,0,NULL),
(64,'capworkflowexecution','WorkflowParamName','Input',NULL,0,NULL),
(65,'capworkflowexecution','SecurityKey','SecurityKey',NULL,0,NULL),
(66,'capworkflowexecution','Sequence','LicenseType,ApplicationName,Date,Validity,HostName,UserName',NULL,0,NULL),
(67,'capworkflowexecution','TimeLimit','1000',NULL,0,NULL),
(68,'capworkflowexecution','PassWFOCRPath','True',NULL,0,NULL),
(69,'capworkflowexecution','SaveOCRImagesDest','db',NULL,0,NULL),
(70,'capworkflowexecution','CurrentDirectory','###',NULL,0,NULL),
(71,'capworkflowexecution','GetTemplateApiUrl','api/ocr/TextFromImageBytes',NULL,0,NULL),
(72,'capworkflowexecution','IsBotFactoryEnabled','False',NULL,0,NULL),
(73,'capworkflowexecution','BotFactoryApi','http://localhost:8081/',NULL,0,NULL),
(74,'capworkflowexecution','VaultToolName','CAP',NULL,0,NULL),
(75,'capworkflowexecution','SaveFindControlTemplateAndScreenshot','False',NULL,0,NULL),
(76,'capworkflowexecution','ConfidenceForImageMatch','75',NULL,0,NULL),
(77,'capworkflowexecution','headlessNodeUrl','http://punhjw380958d:8090/nodeHeadLess',NULL,0,NULL),
(78,'capworkflowexecution','IsMongoDB','True',NULL,0,NULL),
(79,'capworkflowexecution','LogTableName','Log',NULL,0,NULL),
(80,'capworkflowexecution','LogTableName','Log',NULL,0,NULL),
(81,'capuploadUtility','IsClassCode','0',NULL,0,NULL),
(82,'capuploadUtility','VbsClassCode','~LibraryJsonParse.vbs',NULL,0,NULL),
(83,'capuploadUtility','WFFilePath','~LibraryWFFiles.zip',NULL,0,NULL),
(84,'capuploadUtility','IsWFFiles','~LibraryWFFiles.zip',NULL,0,NULL),
(85,'capuploadUtility','PackagePath','D:Package.zip',NULL,0,NULL),
(86,'capuploadUtility','ChunkSizeInKB','3072',NULL,0,NULL),
(87,'capuploadUtility','IsReleaseBinary','1',NULL,0,NULL),
(88,'capuploadUtility','MySQLDBName','icap16dec',NULL,0,NULL),
(89,'capuploadUtility','ReleasePath','D:	empicap1.3.9.zip',NULL,0,NULL),
(90,'cappurge','Buffer','20000',NULL,0,NULL),
(91,'cappurge','LogDuration','100',NULL,0,NULL),
(92,'cappurge','WorkflowTxnDuration','100',NULL,0,NULL),
(93,'cappurge','ProbeTxnDuration','360',NULL,0,NULL),
(94,'capprocessscript','OutputZipPath','D:SAPTest',NULL,0,NULL),
(95,'capprocessscript','ScriptPath','D:SAPTestScript.vbs',NULL,0,NULL),
(96,'capprocessscript','Properties','text,focusDate,selected,key',NULL,0,NULL),
(97,'capinsertreleasescript','ReleasePath','D:\\Config_Templates\\Config_Templates\\',NULL,0,NULL),
(98,'capinsertreleasescript','ReleaseType','Partial',NULL,0,NULL),
(99,'capdistributewf','ApplicationName','Leo1311',NULL,0,NULL),
(100,'capdistributewf','Instance','PrimaryBotmonitor',NULL,0,NULL),
(101,'capdistributewf','HeartbeatThreshold','5',NULL,0,NULL),
(102,'capdistributewf','PortfolioName','Live Enterprise',NULL,0,NULL),
(103,'capbotmonitor','MySQLDBName','iampicappng',NULL,0,NULL),
(104,'capbotmonitor','Instance','PrimaryBotmonitor',NULL,0,NULL),
(105,'capbotmonitor','HeartbeatThreshold','5',NULL,0,NULL),
(106,'capbotmonitor','SREEnabled','True',NULL,0,NULL),
(107,'capbotmonitor','AppId','1',NULL,0,NULL),
(108,'capbotmonitor','IsReleaseBinary','1',NULL,0,NULL),
(109,'capbotmonitor','ReleasePath','D:ICAP_workbenchEditorWithAgent.zip',NULL,0,NULL),
(110,'capbotmonitor','IsPackageBinary','0',NULL,0,NULL),
(111,'capbotmonitor','PackagePath','D:Package.zip',NULL,0,NULL),
(112,'capbotmonitor','IsWFFiles','1',NULL,0,NULL),
(113,'capbotmonitor','WFFilePath','~LibraryWFFiles.zip',NULL,0,NULL),
(114,'capbotmonitor','IsClassCode','1',NULL,0,NULL),
(115,'capbotmonitor','VbsClassCode','~LibraryJsonParse.vbs',NULL,0,NULL),
(116,'capbotmonitor','inactivityThreshold','10',NULL,0,NULL),
(117,'capbotmonitor','Host','#SMTPIP#',NULL,0,NULL),
(118,'capbotmonitor','Port','#PORT#',NULL,0,NULL),
(119,'capbotmonitor','SSL','True',NULL,0,NULL),
(120,'capbotmonitor','FromEmail','#FROMEMAIL#',NULL,0,NULL),
(121,'capbotmonitor','ToEmail','#TOEMAIL#',NULL,0,NULL),
(122,'capbotmonitor','Username','divyansh.gupta01',NULL,0,NULL),
(123,'capbotmonitor','Pass','pass',NULL,0,NULL),
(124,'capbotmonitor','sleep','5',NULL,0,NULL),
(125,'capbotmonitor','sendmail','False',NULL,0,NULL),
(126,'capbotmonitor','Thresholdmins','5',NULL,0,NULL),
(127,'capbotmonitor','PortfolioNames','PNG',NULL,0,NULL),
(128,'capbotmonitor','ApplicationNames','MONITORING_APP',NULL,0,NULL),
(129,'capbotmonitor','NodeNames','PUNHJW472620D,VICTADPST-06',NULL,0,NULL),
(130,'capautodeployer','SharedPath',' ',NULL,0,NULL),
(131,'capautodeployer','SaveLastNScreenshots','3',NULL,0,NULL),
(132,'capappavailability','Instance','PrimaryMailUtility',NULL,0,NULL),
(133,'capappavailability','HeartbeatThreshold','5',NULL,0,NULL),
(134,'capappavailability','AbortKeywords','protocol##chromium##timeout##network##protocol##page not found',NULL,0,NULL),
(135,'capappavailability','AbortExclusionKeywords','protocol##chromium##timeout##network##protocol##page not found',NULL,0,NULL),
(136,'capappavailability','AbortEmailRecipients','kirti.bodekar@lfn.com',NULL,0,NULL),
(137,'capappavailability','AbortEmailRecipients','kirti.bodekar@lfn.com',NULL,0,NULL),
(138,'capappavailability','AbortRec','1',NULL,0,NULL),
(139,'capappavailability','DownTimeExpiry','4',NULL,0,NULL),
(140,'capappavailability','Host','192.168.105.74',NULL,0,NULL),
(141,'capappavailability','Port','25',NULL,0,NULL),
(142,'capappavailability','SSL','True',NULL,0,NULL),
(143,'capappavailability','thresholdpercent','5',NULL,0,NULL),
(144,'capappavailability','FromEmail','divyansh.gupta01@lfn.com',NULL,0,NULL),
(145,'capappavailability','FromMailServer','divyansh.gupta01@lfn.com',NULL,0,NULL),
(146,'capappavailability','ToMailServer','divyansh.gupta01@lfn.com',NULL,0,NULL),
(147,'capappavailability','Username','Rajesh_Thankappan',NULL,0,NULL),
(148,'capappavailability','Pass','Acer@2025',NULL,0,NULL),
(149,'capappavailability','ServiceNowUrl','https://pggeiide3.service-now.com_dummy/api/now/import/u_incident' ,NULL,0,NULL),
(150,'capappavailability','ServiceNowGetUrl','https://pgglobalenterpriseuat.service-now.com/api/now/table/incident' ,NULL,0,NULL),
(151,'capappavailability','ServiceNowCred','servicenowintl10',NULL,0,NULL),
(152,'capappavailability','ServiceNowFormat','XML',NULL,0,NULL),
(154,'Generic','EnableFileLog','True',NULL,0,NULL),
(156,'capagent','replacementTemplate','###',NULL,0,NULL),
(157,'capgeneratetrigger','Nodeids','[]',NULL,0,NULL),
(158,'capgeneratetrigger','releaseid','#ReleaseId#',NULL,0,NULL),
(159,'capgeneratetrigger','isrelease','True',NULL,0,NULL),
(160,'capgeneratetrigger','isconfig','True',NULL,0,NULL),
(161,'capgeneratetrigger','level','ERROR',NULL,0,NULL),
(162,'capgeneratetrigger','BotScreenShotMode','File',NULL,0,NULL),
(163,'capgeneratetrigger','BotScreenShotThresholdDays','10',NULL,0,NULL),
(164,'capgeneratetrigger','bufferSize','5',NULL,0,NULL),
(165,'capgeneratetrigger','screenshotday','10',NULL,0,NULL),
(166,'capgeneratetrigger','retrythreshold','3',NULL,0,NULL),
(167,'capgeneratetrigger','headlessSS','true',NULL,0,NULL),
(168,'capdistributewf','sleepTime','1',NULL,0,NULL);

SET IDENTITY_INSERT cap_config OFF
GO
