cp /root/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar  /app/lib/
cp /root/.m2/repository/io/micrometer/micrometer-observation/1.13.6/micrometer-observation-1.13.6.jar  /app/lib/
cp /root/.m2/repository/io/micrometer/micrometer-registry-prometheus/1.13.6/micrometer-registry-prometheus-1.13.6.jar  /app/lib/
cp /root/.m2/repository/io/micrometer/micrometer-jakarta9/1.13.6/micrometer-jakarta9-1.13.6.jar  /app/lib/
cp /root/.m2/repository/io/micrometer/micrometer-core/1.13.6/micrometer-core-1.13.6.jar  /app/lib/
cp /root/.m2/repository/io/micrometer/micrometer-commons/1.13.6/micrometer-commons-1.13.6.jar  /app/lib/
cp /root/.m2/repository/io/smallrye/jandex/3.1.2/jandex-3.1.2.jar  /app/lib/
cp /root/.m2/repository/io/swagger/core/v3/swagger-core/2.2.8/swagger-core-2.2.8.jar  /app/lib/
cp /root/.m2/repository/io/swagger/core/v3/swagger-annotations/2.2.8/swagger-annotations-2.2.8.jar  /app/lib/
cp /root/.m2/repository/io/swagger/core/v3/swagger-models/2.2.8/swagger-models-2.2.8.jar  /app/lib/
cp /root/.m2/repository/io/minio/minio/8.2.0/minio-8.2.0.jar  /app/lib/
cp /root/.m2/repository/io/github/classgraph/classgraph/4.8.138/classgraph-4.8.138.jar  /app/lib/
cp /root/.m2/repository/io/opencensus/opencensus-contrib-http-util/0.31.1/opencensus-contrib-http-util-0.31.1.jar  /app/lib/
cp /root/.m2/repository/io/opencensus/opencensus-api/0.31.1/opencensus-api-0.31.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-services/1.67.1/grpc-services-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-alts/1.67.1/grpc-alts-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-inprocess/1.67.1/grpc-inprocess-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-core/1.67.1/grpc-core-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-googleapis/1.67.1/grpc-googleapis-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-protobuf/1.67.1/grpc-protobuf-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-xds/1.67.1/grpc-xds-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-stub/1.67.1/grpc-stub-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-util/1.67.1/grpc-util-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-grpclb/1.67.1/grpc-grpclb-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-netty-shaded/1.67.1/grpc-netty-shaded-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-context/1.67.1/grpc-context-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-context/1.60.1/grpc-context-1.60.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-api/1.67.1/grpc-api-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-api/1.60.1/grpc-api-1.60.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-protobuf-lite/1.67.1/grpc-protobuf-lite-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/grpc/grpc-auth/1.67.1/grpc-auth-1.67.1.jar  /app/lib/
cp /root/.m2/repository/io/perfmark/perfmark-api/0.27.0/perfmark-api-0.27.0.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.114.Final/netty-transport-native-unix-common-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-tcnative-classes/2.0.66.Final/netty-tcnative-classes-2.0.66.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-memcache/4.1.114.Final/netty-codec-memcache-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-udt/4.1.114.Final/netty-transport-udt-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-redis/4.1.114.Final/netty-codec-redis-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport/4.1.114.Final/netty-transport-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec/4.1.114.Final/netty-codec-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-native-epoll/4.1.114.Final/netty-transport-native-epoll-4.1.114.Final-linux-riscv64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-native-epoll/4.1.114.Final/netty-transport-native-epoll-4.1.114.Final-linux-aarch_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-native-epoll/4.1.114.Final/netty-transport-native-epoll-4.1.114.Final-linux-x86_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-smtp/4.1.114.Final/netty-codec-smtp-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/incubator/netty-incubator-codec-classes-quic/0.0.68.Final/netty-incubator-codec-classes-quic-0.0.68.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/incubator/netty-incubator-codec-native-quic/0.0.68.Final/netty-incubator-codec-native-quic-0.0.68.Final-linux-x86_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-rxtx/4.1.114.Final/netty-transport-rxtx-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-resolver-dns-native-macos/4.1.114.Final/netty-resolver-dns-native-macos-4.1.114.Final-osx-x86_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-resolver-dns-native-macos/4.1.114.Final/netty-resolver-dns-native-macos-4.1.114.Final-osx-aarch_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-handler-proxy/4.1.114.Final/netty-handler-proxy-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-http/4.1.114.Final/netty-codec-http-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-http/4.1.86.Final/netty-codec-http-4.1.86.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-classes-kqueue/4.1.114.Final/netty-transport-classes-kqueue-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-haproxy/4.1.114.Final/netty-codec-haproxy-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-http2/4.1.111.Final/netty-codec-http2-4.1.111.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-http2/4.1.100.Final/netty-codec-http2-4.1.100.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-http2/4.1.115.Final/netty-codec-http2-4.1.115.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-handler/4.1.108.Final/netty-handler-4.1.108.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-handler/4.1.100.Final/netty-handler-4.1.100.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-mqtt/4.1.114.Final/netty-codec-mqtt-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-dns/4.1.114.Final/netty-codec-dns-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.114.Final/netty-transport-native-kqueue-4.1.114.Final-osx-x86_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.114.Final/netty-transport-native-kqueue-4.1.114.Final-osx-aarch_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-socks/4.1.114.Final/netty-codec-socks-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-classes-epoll/4.1.114.Final/netty-transport-classes-epoll-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-resolver-dns/4.1.114.Final/netty-resolver-dns-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-resolver-dns-classes-macos/4.1.114.Final/netty-resolver-dns-classes-macos-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-xml/4.1.114.Final/netty-codec-xml-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-handler-ssl-ocsp/4.1.114.Final/netty-handler-ssl-ocsp-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-common/4.1.115.Final/netty-common-4.1.115.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-codec-stomp/4.1.114.Final/netty-codec-stomp-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-buffer/4.1.114.Final/netty-buffer-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.66.Final/netty-tcnative-boringssl-static-2.0.66.Final-osx-x86_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.66.Final/netty-tcnative-boringssl-static-2.0.66.Final-osx-aarch_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.66.Final/netty-tcnative-boringssl-static-2.0.66.Final-windows-x86_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.66.Final/netty-tcnative-boringssl-static-2.0.66.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.66.Final/netty-tcnative-boringssl-static-2.0.66.Final-linux-x86_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.66.Final/netty-tcnative-boringssl-static-2.0.66.Final-linux-aarch_64.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-resolver/4.1.114.Final/netty-resolver-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-transport-sctp/4.1.114.Final/netty-transport-sctp-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-all/4.1.115.Final/netty-all-4.1.115.Final.jar  /app/lib/
cp /root/.m2/repository/io/netty/netty-all/4.1.114.Final/netty-all-4.1.114.Final.jar  /app/lib/
cp /root/.m2/repository/io/projectreactor/reactor-core/3.6.11/reactor-core-3.6.11.jar  /app/lib/
cp /root/.m2/repository/io/projectreactor/reactor-test/3.6.11/reactor-test-3.6.11.jar  /app/lib/
cp /root/.m2/repository/io/projectreactor/netty/incubator/reactor-netty-incubator-quic/0.1.23/reactor-netty-incubator-quic-0.1.23.jar  /app/lib/
cp /root/.m2/repository/io/projectreactor/netty/reactor-netty-core/1.1.23/reactor-netty-core-1.1.23.jar  /app/lib/
cp /root/.m2/repository/io/projectreactor/netty/reactor-netty/1.1.23/reactor-netty-1.1.23.jar  /app/lib/
cp /root/.m2/repository/io/projectreactor/netty/reactor-netty-http/1.1.13/reactor-netty-http-1.1.13.jar  /app/lib/
cp /root/.m2/repository/io/gsonfire/gson-fire/1.8.5/gson-fire-1.8.5.jar  /app/lib/
cp /root/.m2/repository/io/prometheus/prometheus-metrics-shaded-protobuf/1.2.1/prometheus-metrics-shaded-protobuf-1.2.1.jar  /app/lib/
cp /root/.m2/repository/io/prometheus/prometheus-metrics-tracer-common/1.2.1/prometheus-metrics-tracer-common-1.2.1.jar  /app/lib/
cp /root/.m2/repository/io/prometheus/prometheus-metrics-exposition-formats/1.2.1/prometheus-metrics-exposition-formats-1.2.1.jar  /app/lib/
cp /root/.m2/repository/io/prometheus/prometheus-metrics-model/1.2.1/prometheus-metrics-model-1.2.1.jar  /app/lib/
cp /root/.m2/repository/io/prometheus/prometheus-metrics-core/1.2.1/prometheus-metrics-core-1.2.1.jar  /app/lib/
cp /root/.m2/repository/io/prometheus/prometheus-metrics-config/1.2.1/prometheus-metrics-config-1.2.1.jar  /app/lib/
cp /root/.m2/repository/io/jsonwebtoken/jjwt-jackson/0.11.2/jjwt-jackson-0.11.2.jar  /app/lib/
cp /root/.m2/repository/io/jsonwebtoken/jjwt-api/0.11.2/jjwt-api-0.11.2.jar  /app/lib/
cp /root/.m2/repository/io/jsonwebtoken/jjwt-impl/0.11.2/jjwt-impl-0.11.2.jar  /app/lib/
cp /root/.m2/repository/info/picocli/picocli/4.7.6/picocli-4.7.6.jar  /app/lib/
cp /root/.m2/repository/info/picocli/picocli/4.7.5/picocli-4.7.5.jar  /app/lib/
cp /root/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar  /app/lib/
cp /root/.m2/repository/commons-codec/commons-codec/1.16.1/commons-codec-1.16.1.jar  /app/lib/
cp /root/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar  /app/lib/
cp /root/.m2/repository/com/h2database/h2/2.2.224/h2-2.2.224.jar  /app/lib/
cp /root/.m2/repository/com/adobe/xmp/xmpcore/6.1.11/xmpcore-6.1.11.jar  /app/lib/
cp /root/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-storage-internal-avro/12.14.0/azure-storage-internal-avro-12.14.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core-http-netty/1.9.0/azure-core-http-netty-1.9.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core-http-netty/1.15.5/azure-core-http-netty-1.15.5.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core-http-netty/1.15.6/azure-core-http-netty-1.15.6.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-ai-textanalytics/5.5.0/azure-ai-textanalytics-5.5.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-ai-openai/1.0.0-beta.10/azure-ai-openai-1.0.0-beta.10.jar  /app/lib/
cp /root/.m2/repository/com/azure/spring/spring-cloud-azure-core/5.13.0/spring-cloud-azure-core-5.13.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/spring/spring-cloud-azure-autoconfigure/5.13.0/spring-cloud-azure-autoconfigure-5.13.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/spring/spring-cloud-azure-service/5.13.0/spring-cloud-azure-service-5.13.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/spring/spring-cloud-azure-starter/5.13.0/spring-cloud-azure-starter-5.13.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/spring/spring-cloud-azure-starter-keyvault-secrets/5.13.0/spring-cloud-azure-starter-keyvault-secrets-5.13.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-identity/1.14.0/azure-identity-1.14.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-xml/1.1.0/azure-xml-1.1.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-xml/1.0.0/azure-xml-1.0.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-storage-blob/12.29.0/azure-storage-blob-12.29.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core-amqp/2.9.4/azure-core-amqp-2.9.4.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-storage-common/12.28.0/azure-storage-common-12.28.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core/1.54.1/azure-core-1.54.1.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core/1.50.0/azure-core-1.50.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core/1.48.0/azure-core-1.48.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-json/1.1.0/azure-json-1.1.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-json/1.3.0/azure-json-1.3.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-security-keyvault-secrets/4.8.3/azure-security-keyvault-secrets-4.8.3.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core-management/1.14.0/azure-core-management-1.14.0.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core-http-okhttp/1.12.6/azure-core-http-okhttp-1.12.6.jar  /app/lib/
cp /root/.m2/repository/com/azure/azure-core-http-okhttp/1.12.0/azure-core-http-okhttp-1.12.0.jar  /app/lib/
cp /root/.m2/repository/com/thoughtworks/qdox/qdox/1.12.1/qdox-1.12.1.jar  /app/lib/
cp /root/.m2/repository/com/thoughtworks/qdox/qdox/2.0.3/qdox-2.0.3.jar  /app/lib/
cp /root/.m2/repository/com/thoughtworks/qdox/qdox/2.0-M9/qdox-2.0-M9.jar  /app/lib/
cp /root/.m2/repository/com/microsoft/azure/qpid-proton-j-extensions/1.2.5/qpid-proton-j-extensions-1.2.5.jar  /app/lib/
cp /root/.m2/repository/com/microsoft/azure/msal4j-persistence-extension/1.3.0/msal4j-persistence-extension-1.3.0.jar  /app/lib/
cp /root/.m2/repository/com/microsoft/azure/msal4j/1.17.2/msal4j-1.17.2.jar  /app/lib/
cp /root/.m2/repository/com/microsoft/graph/microsoft-graph/5.9.0/microsoft-graph-5.9.0.jar  /app/lib/
cp /root/.m2/repository/com/microsoft/graph/microsoft-graph-core/2.0.10/microsoft-graph-core-2.0.10.jar  /app/lib/
cp /root/.m2/repository/com/microsoft/sqlserver/mssql-jdbc/12.6.4.jre11/mssql-jdbc-12.6.4.jre11.jar  /app/lib/
cp /root/.m2/repository/com/carrotsearch/thirdparty/simple-xml-safe/2.7.1/simple-xml-safe-2.7.1.jar  /app/lib/
cp /root/.m2/repository/com/pff/java-libpst/0.9.3/java-libpst-0.9.3.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-ec2/1.11.163/aws-java-sdk-ec2-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-sns/1.11.163/aws-java-sdk-sns-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-elasticloadbalancingv2/1.11.163/aws-java-sdk-elasticloadbalancingv2-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-models/1.11.163/aws-java-sdk-models-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cloudformation/1.11.163/aws-java-sdk-cloudformation-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-lexmodelbuilding/1.11.163/aws-java-sdk-lexmodelbuilding-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-elasticloadbalancing/1.11.163/aws-java-sdk-elasticloadbalancing-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-dms/1.11.163/aws-java-sdk-dms-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-batch/1.11.163/aws-java-sdk-batch-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-core/1.12.773/aws-java-sdk-core-1.12.773.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-core/1.12.261/aws-java-sdk-core-1.12.261.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-core/1.11.163/aws-java-sdk-core-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-core/1.12.158/aws-java-sdk-core-1.12.158.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-efs/1.11.163/aws-java-sdk-efs-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-waf/1.11.163/aws-java-sdk-waf-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-codecommit/1.11.163/aws-java-sdk-codecommit-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-sts/1.11.163/aws-java-sdk-sts-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-codebuild/1.11.163/aws-java-sdk-codebuild-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-ecs/1.11.163/aws-java-sdk-ecs-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-simpleworkflow/1.11.163/aws-java-sdk-simpleworkflow-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-directconnect/1.11.163/aws-java-sdk-directconnect-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-logs/1.11.163/aws-java-sdk-logs-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-ecr/1.11.163/aws-java-sdk-ecr-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-marketplacemeteringservice/1.11.163/aws-java-sdk-marketplacemeteringservice-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-codestar/1.11.163/aws-java-sdk-codestar-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cloudtrail/1.11.163/aws-java-sdk-cloudtrail-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-datapipeline/1.11.163/aws-java-sdk-datapipeline-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cloudfront/1.11.163/aws-java-sdk-cloudfront-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-shield/1.11.163/aws-java-sdk-shield-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-acm/1.11.163/aws-java-sdk-acm-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-marketplacecommerceanalytics/1.11.163/aws-java-sdk-marketplacecommerceanalytics-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-health/1.11.163/aws-java-sdk-health-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-athena/1.11.163/aws-java-sdk-athena-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-organizations/1.11.163/aws-java-sdk-organizations-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-importexport/1.11.163/aws-java-sdk-importexport-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-rds/1.11.163/aws-java-sdk-rds-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-opsworks/1.11.163/aws-java-sdk-opsworks-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-support/1.11.163/aws-java-sdk-support-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cognitoidp/1.11.163/aws-java-sdk-cognitoidp-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-sqs/1.11.163/aws-java-sdk-sqs-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-dax/1.11.163/aws-java-sdk-dax-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-machinelearning/1.11.163/aws-java-sdk-machinelearning-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-api-gateway/1.11.163/aws-java-sdk-api-gateway-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-elasticache/1.11.163/aws-java-sdk-elasticache-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-elasticbeanstalk/1.11.163/aws-java-sdk-elasticbeanstalk-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-workspaces/1.11.163/aws-java-sdk-workspaces-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-opsworkscm/1.11.163/aws-java-sdk-opsworkscm-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cloudhsm/1.11.163/aws-java-sdk-cloudhsm-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-pinpoint/1.11.163/aws-java-sdk-pinpoint-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-s3/1.12.773/aws-java-sdk-s3-1.12.773.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-s3/1.12.261/aws-java-sdk-s3-1.12.261.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-s3/1.11.163/aws-java-sdk-s3-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-s3/1.11.923/aws-java-sdk-s3-1.11.923.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-greengrass/1.11.163/aws-java-sdk-greengrass-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-mechanicalturkrequester/1.11.163/aws-java-sdk-mechanicalturkrequester-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-marketplaceentitlement/1.11.163/aws-java-sdk-marketplaceentitlement-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-gamelift/1.11.163/aws-java-sdk-gamelift-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-rekognition/1.11.163/aws-java-sdk-rekognition-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-discovery/1.11.163/aws-java-sdk-discovery-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-directory/1.11.163/aws-java-sdk-directory-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-sagemaker/1.12.158/aws-java-sdk-sagemaker-1.12.158.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-kinesis/1.11.163/aws-java-sdk-kinesis-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-elasticsearch/1.11.163/aws-java-sdk-elasticsearch-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cognitoidentity/1.11.163/aws-java-sdk-cognitoidentity-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-storagegateway/1.11.163/aws-java-sdk-storagegateway-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-servermigration/1.11.163/aws-java-sdk-servermigration-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk/1.11.163/aws-java-sdk-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-elastictranscoder/1.11.163/aws-java-sdk-elastictranscoder-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-lambda/1.11.163/aws-java-sdk-lambda-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cloudwatchmetrics/1.11.163/aws-java-sdk-cloudwatchmetrics-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/jmespath-java/1.12.773/jmespath-java-1.12.773.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/jmespath-java/1.12.261/jmespath-java-1.12.261.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/jmespath-java/1.11.163/jmespath-java-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/jmespath-java/1.12.158/jmespath-java-1.12.158.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-config/1.11.163/aws-java-sdk-config-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-workdocs/1.11.163/aws-java-sdk-workdocs-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-iot/1.11.163/aws-java-sdk-iot-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cognitosync/1.11.163/aws-java-sdk-cognitosync-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-polly/1.11.163/aws-java-sdk-polly-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-servicecatalog/1.11.163/aws-java-sdk-servicecatalog-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-lex/1.11.163/aws-java-sdk-lex-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-ses/1.11.163/aws-java-sdk-ses-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-codepipeline/1.11.163/aws-java-sdk-codepipeline-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-appstream/1.11.163/aws-java-sdk-appstream-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-stepfunctions/1.11.163/aws-java-sdk-stepfunctions-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-emr/1.11.163/aws-java-sdk-emr-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-codedeploy/1.11.163/aws-java-sdk-codedeploy-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-autoscaling/1.11.163/aws-java-sdk-autoscaling-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-devicefarm/1.11.163/aws-java-sdk-devicefarm-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-costandusagereport/1.11.163/aws-java-sdk-costandusagereport-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-clouddirectory/1.11.163/aws-java-sdk-clouddirectory-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-inspector/1.11.163/aws-java-sdk-inspector-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cloudsearch/1.11.163/aws-java-sdk-cloudsearch-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-dynamodb/1.11.163/aws-java-sdk-dynamodb-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-cloudwatch/1.11.163/aws-java-sdk-cloudwatch-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-xray/1.11.163/aws-java-sdk-xray-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-lightsail/1.11.163/aws-java-sdk-lightsail-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-redshift/1.11.163/aws-java-sdk-redshift-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-events/1.11.163/aws-java-sdk-events-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-ssm/1.11.163/aws-java-sdk-ssm-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-swf-libraries/1.11.22/aws-java-sdk-swf-libraries-1.11.22.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-applicationautoscaling/1.11.163/aws-java-sdk-applicationautoscaling-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-route53/1.11.163/aws-java-sdk-route53-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-resourcegroupstaggingapi/1.11.163/aws-java-sdk-resourcegroupstaggingapi-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-iam/1.11.163/aws-java-sdk-iam-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-kms/1.12.773/aws-java-sdk-kms-1.12.773.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-kms/1.12.261/aws-java-sdk-kms-1.12.261.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-kms/1.11.163/aws-java-sdk-kms-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-kms/1.11.923/aws-java-sdk-kms-1.11.923.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-snowball/1.11.163/aws-java-sdk-snowball-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-simpledb/1.11.163/aws-java-sdk-simpledb-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-glacier/1.11.163/aws-java-sdk-glacier-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/amazonaws/aws-java-sdk-budgets/1.11.163/aws-java-sdk-budgets-1.11.163.jar  /app/lib/
cp /root/.m2/repository/com/mchange/mchange-commons-java/0.2.15/mchange-commons-java-0.2.15.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/classmate/1.7.0/classmate-1.7.0.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/woodstox/woodstox-core/6.7.0/woodstox-core-6.7.0.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.17.2/jackson-dataformat-yaml-2.17.2.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.17.2/jackson-dataformat-cbor-2.17.2.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.17.2/jackson-dataformat-xml-2.17.2.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.17.2/jackson-module-parameter-names-2.17.2.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.17.2/jackson-datatype-jsr310-2.17.2.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.17.2/jackson-datatype-jdk8-2.17.2.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.17.2/jackson-annotations-2.17.2.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.17.2/jackson-databind-2.17.2.jar  /app/lib/
cp /root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.17.2/jackson-core-2.17.2.jar  /app/lib/
cp /root/.m2/repository/com/infosys/common-lib-rest/3.3-SNAPSHOT/common-lib-rest-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/iamp-lib-usm/3.3-SNAPSHOT/iamp-lib-usm-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/ai/comm-lib-util/3.3-SNAPSHOT/comm-lib-util-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/ai/comm-lib-secrets/3.3-SNAPSHOT/comm-lib-secrets-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/ai/comm-secrets-app/3.3-SNAPSHOT/comm-secrets-app-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/icip/icip-lib-search/3.3-SNAPSHOT/icip-lib-search-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/icip/icip-lib-fsvr/3.3-SNAPSHOT/icip-lib-fsvr-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/icip/icip-lib-jobs/3.3-SNAPSHOT/icip-lib-jobs-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/icip/icip-lib-mod/3.3-SNAPSHOT/icip-lib-mod-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/icip/plugins/icip-adp-aicloud/3.3-SNAPSHOT/icip-adp-aicloud-3.3-SNAPSHOT.jar  /app/plugins/
cp /root/.m2/repository/com/infosys/icets/icip/plugins/icip-adp-s3/3.3-SNAPSHOT/icip-adp-s3-3.3-SNAPSHOT.jar  /app/plugins/
cp /root/.m2/repository/com/infosys/icets/icip/plugins/icip-adp-aws-sagemaker/3.3-SNAPSHOT/icip-adp-aws-sagemaker-3.3-SNAPSHOT.jar  /app/plugins/
cp /root/.m2/repository/com/infosys/icets/icip/plugins/icip-adp-remote/3.3-SNAPSHOT/icip-adp-remote-3.3-SNAPSHOT.jar  /app/plugins/
cp /root/.m2/repository/com/infosys/icets/icip/plugins/icip-adp-postgresql/3.3-SNAPSHOT/icip-adp-postgresql-3.3-SNAPSHOT.jar  /app/plugins/
cp /root/.m2/repository/com/infosys/icets/icip/plugins/icip-adp-rest/3.3-SNAPSHOT/icip-adp-rest-3.3-SNAPSHOT.jar  /app/plugins/
cp /root/.m2/repository/com/infosys/icets/icip/plugins/icip-adp-mysql/3.3-SNAPSHOT/icip-adp-mysql-3.3-SNAPSHOT.jar  /app/plugins/
cp /root/.m2/repository/com/infosys/icets/icip/icip-lib-evt/3.3-SNAPSHOT/icip-lib-evt-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/icip/icip-lib-mlops/3.3-SNAPSHOT/icip-lib-mlops-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/icip/icip-lib-adp/3.3-SNAPSHOT/icip-lib-adp-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/icets/icip/icip-lib-iai/3.3-SNAPSHOT/icip-lib-iai-3.3-SNAPSHOT.jar  /app/modules/
cp /root/.m2/repository/com/infosys/common-app/3.3-SNAPSHOT/common-app-3.3-SNAPSHOT.jar  /app/
cp /root/.m2/repository/com/squareup/okio/okio-jvm/3.6.0/okio-jvm-3.6.0.jar  /app/lib/
cp /root/.m2/repository/com/squareup/okio/okio-jvm/3.4.0/okio-jvm-3.4.0.jar  /app/lib/
cp /root/.m2/repository/com/squareup/okio/okio-jvm/3.9.1/okio-jvm-3.9.1.jar  /app/lib/
cp /root/.m2/repository/com/squareup/okio/okio/3.6.0/okio-3.6.0.jar  /app/lib/
cp /root/.m2/repository/com/squareup/okio/okio/2.8.0/okio-2.8.0.jar  /app/lib/
cp /root/.m2/repository/com/squareup/okio/okio/3.9.1/okio-3.9.1.jar  /app/lib/
cp /root/.m2/repository/com/squareup/okhttp3/logging-interceptor/4.12.0/logging-interceptor-4.12.0.jar  /app/lib/
cp /root/.m2/repository/com/squareup/okhttp3/logging-interceptor/4.9.0/logging-interceptor-4.9.0.jar  /app/lib/
cp /root/.m2/repository/com/squareup/okhttp3/okhttp/4.12.0/okhttp-4.12.0.jar  /app/lib/
cp /root/.m2/repository/com/squareup/okhttp3/okhttp/4.9.0/okhttp-4.9.0.jar  /app/lib/
cp /root/.m2/repository/com/google/guava/guava/33.1.0-jre/guava-33.1.0-jre.jar  /app/lib/
cp /root/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar  /app/lib/
cp /root/.m2/repository/com/google/guava/failureaccess/1.0.2/failureaccess-1.0.2.jar  /app/lib/
cp /root/.m2/repository/com/google/code/gson/gson/2.11.0/gson-2.11.0.jar  /app/lib/
cp /root/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar  /app/lib/
cp /root/.m2/repository/com/google/errorprone/error_prone_annotations/2.30.0/error_prone_annotations-2.30.0.jar  /app/lib/
cp /root/.m2/repository/com/google/errorprone/error_prone_annotations/2.26.1/error_prone_annotations-2.26.1.jar  /app/lib/
cp /root/.m2/repository/com/google/errorprone/error_prone_annotations/2.27.0/error_prone_annotations-2.27.0.jar  /app/lib/
cp /root/.m2/repository/com/google/android/annotations/4.1.1.4/annotations-4.1.1.4.jar  /app/lib/
cp /root/.m2/repository/com/google/re2j/re2j/1.7/re2j-1.7.jar  /app/lib/
cp /root/.m2/repository/com/google/auth/google-auth-library-credentials/1.28.0/google-auth-library-credentials-1.28.0.jar  /app/lib/
cp /root/.m2/repository/com/google/auth/google-auth-library-credentials/1.24.1/google-auth-library-credentials-1.24.1.jar  /app/lib/
cp /root/.m2/repository/com/google/auth/google-auth-library-oauth2-http/1.24.1/google-auth-library-oauth2-http-1.24.1.jar  /app/lib/
cp /root/.m2/repository/com/google/auto/value/auto-value-annotations/1.10.4/auto-value-annotations-1.10.4.jar  /app/lib/
cp /root/.m2/repository/com/google/auto/value/auto-value-annotations/1.11.0/auto-value-annotations-1.11.0.jar  /app/lib/
cp /root/.m2/repository/com/google/j2objc/j2objc-annotations/2.8/j2objc-annotations-2.8.jar  /app/lib/
cp /root/.m2/repository/com/google/j2objc/j2objc-annotations/3.0.0/j2objc-annotations-3.0.0.jar  /app/lib/
cp /root/.m2/repository/com/google/cloud/google-cloud-vertexai/1.12.0/google-cloud-vertexai-1.12.0.jar  /app/lib/
cp /root/.m2/repository/com/google/http-client/google-http-client/1.44.2/google-http-client-1.44.2.jar  /app/lib/
cp /root/.m2/repository/com/google/http-client/google-http-client/1.45.0/google-http-client-1.45.0.jar  /app/lib/
cp /root/.m2/repository/com/google/http-client/google-http-client-gson/1.44.2/google-http-client-gson-1.44.2.jar  /app/lib/
cp /root/.m2/repository/com/google/http-client/google-http-client-gson/1.45.0/google-http-client-gson-1.45.0.jar  /app/lib/
cp /root/.m2/repository/com/google/protobuf/protobuf-java/3.24.4/protobuf-java-3.24.4.jar  /app/lib/
cp /root/.m2/repository/com/google/protobuf/protobuf-java/3.25.5/protobuf-java-3.25.5.jar  /app/lib/
cp /root/.m2/repository/com/google/protobuf/protobuf-java-util/3.25.5/protobuf-java-util-3.25.5.jar  /app/lib/
cp /root/.m2/repository/com/google/api/gax-grpc/2.55.0/gax-grpc-2.55.0.jar  /app/lib/
cp /root/.m2/repository/com/google/api/api-common/2.38.0/api-common-2.38.0.jar  /app/lib/
cp /root/.m2/repository/com/google/api/grpc/grpc-google-common-protos/2.46.0/grpc-google-common-protos-2.46.0.jar  /app/lib/
cp /root/.m2/repository/com/google/api/grpc/proto-google-common-protos/2.46.0/proto-google-common-protos-2.46.0.jar  /app/lib/
cp /root/.m2/repository/com/google/api/grpc/proto-google-iam-v1/1.41.0/proto-google-iam-v1-1.41.0.jar  /app/lib/
cp /root/.m2/repository/com/google/api/grpc/grpc-google-iam-v1/1.41.0/grpc-google-iam-v1-1.41.0.jar  /app/lib/
cp /root/.m2/repository/com/google/api/grpc/proto-google-cloud-vertexai-v1/1.12.0/proto-google-cloud-vertexai-v1-1.12.0.jar  /app/lib/
cp /root/.m2/repository/com/google/api/gax/2.55.0/gax-2.55.0.jar  /app/lib/
cp /root/.m2/repository/com/google/api/gax-httpjson/2.55.0/gax-httpjson-2.55.0.jar  /app/lib/
cp /root/.m2/repository/com/github/jai-imageio/jai-imageio-core/1.4.0/jai-imageio-core-1.4.0.jar  /app/lib/
cp /root/.m2/repository/com/github/luben/zstd-jni/1.5.5-2/zstd-jni-1.5.5-2.jar  /app/lib/
cp /root/.m2/repository/com/github/javaparser/javaparser-core/3.26.2/javaparser-core-3.26.2.jar  /app/lib/
cp /root/.m2/repository/com/github/albfernandez/juniversalchardet/2.5.0/juniversalchardet-2.5.0.jar  /app/lib/
cp /root/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar  /app/lib/
cp /root/.m2/repository/com/github/virtuald/curvesapi/1.07/curvesapi-1.07.jar  /app/lib/
cp /root/.m2/repository/com/github/junrar/junrar/7.5.5/junrar-7.5.5.jar  /app/lib/
cp /root/.m2/repository/com/epam/parso/2.0.14/parso-2.0.14.jar  /app/lib/
cp /root/.m2/repository/com/beust/jcommander/1.82/jcommander-1.82.jar  /app/lib/
cp /root/.m2/repository/com/drewnoakes/metadata-extractor/2.19.0/metadata-extractor-2.19.0.jar  /app/lib/
cp /root/.m2/repository/com/rometools/rome/2.1.0/rome-2.1.0.jar  /app/lib/
cp /root/.m2/repository/com/rometools/rome-utils/2.1.0/rome-utils-2.1.0.jar  /app/lib/
cp /root/.m2/repository/com/knuddels/jtokkit/1.1.0/jtokkit-1.1.0.jar  /app/lib/
cp /root/.m2/repository/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar  /app/lib/
cp /root/.m2/repository/com/mysql/mysql-connector-j/8.4.0/mysql-connector-j-8.4.0.jar  /app/lib/
cp /root/.m2/repository/com/nimbusds/nimbus-jose-jwt/9.37.3/nimbus-jose-jwt-9.37.3.jar  /app/lib/
cp /root/.m2/repository/com/nimbusds/nimbus-jose-jwt/9.37.2/nimbus-jose-jwt-9.37.2.jar  /app/lib/
cp /root/.m2/repository/com/nimbusds/lang-tag/1.7/lang-tag-1.7.jar  /app/lib/
cp /root/.m2/repository/com/nimbusds/oauth2-oidc-sdk/11.18/oauth2-oidc-sdk-11.18.jar  /app/lib/
cp /root/.m2/repository/com/nimbusds/content-type/2.3/content-type-2.3.jar  /app/lib/
cp /root/.m2/repository/com/openpojo/openpojo/0.8.13/openpojo-0.8.13.jar  /app/lib/
cp /root/.m2/repository/com/sun/istack/istack-commons-runtime/4.1.2/istack-commons-runtime-4.1.2.jar  /app/lib/
cp /root/.m2/repository/com/sun/activation/jakarta.activation/1.2.2/jakarta.activation-1.2.2.jar  /app/lib/
cp /root/.m2/repository/com/sun/xml/bind/jaxb-impl/2.3.3/jaxb-impl-2.3.3.jar  /app/lib/
cp /root/.m2/repository/com/sun/xml/messaging/saaj/saaj-impl/3.0.4/saaj-impl-3.0.4.jar  /app/lib/
cp /root/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar  /app/lib/
cp /root/.m2/repository/com/googlecode/javaewah/JavaEWAH/1.1.12/JavaEWAH-1.1.12.jar  /app/lib/
cp /root/.m2/repository/com/googlecode/javaewah/JavaEWAH/1.2.3/JavaEWAH-1.2.3.jar  /app/lib/
cp /root/.m2/repository/com/googlecode/plist/dd-plist/1.28/dd-plist-1.28.jar  /app/lib/
cp /root/.m2/repository/com/jayway/jsonpath/json-path/2.9.0/json-path-2.9.0.jar  /app/lib/
cp /root/.m2/repository/com/jayway/jsonpath/json-path/2.5.0/json-path-2.5.0.jar  /app/lib/
cp /root/.m2/repository/com/healthmarketscience/jackcess/jackcess/4.0.7/jackcess-4.0.7.jar  /app/lib/
cp /root/.m2/repository/com/healthmarketscience/jackcess/jackcess-encrypt/4.0.2/jackcess-encrypt-4.0.2.jar  /app/lib/
cp /root/.m2/repository/com/healthmarketscience/sqlbuilder/sqlbuilder/3.0.0/sqlbuilder-3.0.0.jar  /app/lib/
cp /root/.m2/repository/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2.jar  /app/lib/
cp /root/.m2/repository/com/zaxxer/HikariCP/5.1.0/HikariCP-5.1.0.jar  /app/lib/
cp /root/.m2/repository/com/opencsv/opencsv/5.7.1/opencsv-5.7.1.jar  /app/lib/
cp /root/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar  /app/lib/
cp /root/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar  /app/lib/
cp /root/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar  /app/lib/
cp /root/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar  /app/lib/
cp /root/.m2/repository/commons-io/commons-io/2.17.0/commons-io-2.17.0.jar  /app/lib/
cp /root/.m2/repository/commons-io/commons-io/2.12.0/commons-io-2.12.0.jar  /app/lib/
cp /root/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar  /app/lib/
cp /root/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar  /app/lib/
cp /root/.m2/repository/net/minidev/accessors-smart/2.4.9/accessors-smart-2.4.9.jar  /app/lib/
cp /root/.m2/repository/net/minidev/accessors-smart/2.5.1/accessors-smart-2.5.1.jar  /app/lib/
cp /root/.m2/repository/net/minidev/json-smart/2.4.9/json-smart-2.4.9.jar  /app/lib/
cp /root/.m2/repository/net/minidev/json-smart/2.5.1/json-smart-2.5.1.jar  /app/lib/
cp /root/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.19/byte-buddy-agent-1.14.19.jar  /app/lib/
cp /root/.m2/repository/net/bytebuddy/byte-buddy/1.14.19/byte-buddy-1.14.19.jar  /app/lib/
cp /root/.m2/repository/net/java/dev/jna/jna/5.6.0/jna-5.6.0.jar  /app/lib/
cp /root/.m2/repository/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar  /app/lib/
cp /root/.m2/repository/net/java/dev/jna/jna-platform/5.6.0/jna-platform-5.6.0.jar  /app/lib/
cp /root/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar  /app/lib/
cp /root/.m2/repository/javax/cache/cache-api/1.1.1/cache-api-1.1.1.jar  /app/lib/
cp /root/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar  /app/lib/
cp /root/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar  /app/lib/
cp /root/.m2/repository/javax/interceptor/javax.interceptor-api/1.2/javax.interceptor-api-1.2.jar  /app/lib/
cp /root/.m2/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.jar  /app/lib/
cp /root/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar  /app/lib/
cp /root/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar  /app/lib/
cp /root/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.3/jakarta.activation-api-2.1.3.jar  /app/lib/
cp /root/.m2/repository/jakarta/persistence/jakarta.persistence-api/3.1.0/jakarta.persistence-api-3.1.0.jar  /app/lib/
cp /root/.m2/repository/jakarta/transaction/jakarta.transaction-api/2.0.1/jakarta.transaction-api-2.0.1.jar  /app/lib/
cp /root/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.2/jakarta.xml.bind-api-4.0.2.jar  /app/lib/
cp /root/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/3.0.0/jakarta.xml.bind-api-3.0.0.jar  /app/lib/
cp /root/.m2/repository/jakarta/xml/soap/jakarta.xml.soap-api/3.0.2/jakarta.xml.soap-api-3.0.2.jar  /app/lib/
cp /root/.m2/repository/jakarta/xml/ws/jakarta.xml.ws-api/4.0.2/jakarta.xml.ws-api-4.0.2.jar  /app/lib/
cp /root/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar  /app/lib/
cp /root/.m2/repository/jakarta/interceptor/jakarta.interceptor-api/2.1.0/jakarta.interceptor-api-2.1.0.jar  /app/lib/
cp /root/.m2/repository/jakarta/servlet/jakarta.servlet-api/6.0.0/jakarta.servlet-api-6.0.0.jar  /app/lib/
cp /root/.m2/repository/jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.jar  /app/lib/
cp /root/.m2/repository/jline/jline/2.14.6/jline-2.14.6.jar  /app/lib/
cp /root/.m2/repository/ch/qos/logback/logback-classic/1.4.12/logback-classic-1.4.12.jar  /app/lib/
cp /root/.m2/repository/ch/qos/logback/logback-classic/1.5.12/logback-classic-1.5.12.jar  /app/lib/
cp /root/.m2/repository/ch/qos/logback/logback-core/1.4.12/logback-core-1.4.12.jar  /app/lib/
cp /root/.m2/repository/ch/qos/logback/logback-core/1.5.12/logback-core-1.5.12.jar  /app/lib/
cp /root/.m2/repository/commons-fileupload/commons-fileupload/1.5/commons-fileupload-1.5.jar  /app/lib/
cp /root/.m2/repository/logkit/logkit/1.0.1/logkit-1.0.1.jar  /app/lib/
cp /root/.m2/repository/joda-time/joda-time/2.10.6/joda-time-2.10.6.jar  /app/lib/
cp /root/.m2/repository/org/javassist/javassist/3.26.0-GA/javassist-3.26.0-GA.jar  /app/lib/
cp /root/.m2/repository/org/reflections/reflections/0.9.12/reflections-0.9.12.jar  /app/lib/
cp /root/.m2/repository/org/xmlunit/xmlunit-core/2.9.1/xmlunit-core-2.9.1.jar  /app/lib/
cp /root/.m2/repository/org/codelibs/jhighlight/1.1.0/jhighlight-1.1.0.jar  /app/lib/
cp /root/.m2/repository/org/projectlombok/lombok/1.18.30/lombok-1.18.30.jar  /app/lib/
cp /root/.m2/repository/org/tallison/jmatio/1.5/jmatio-1.5.jar  /app/lib/
cp /root/.m2/repository/org/python/jython-standalone/2.7.4/jython-standalone-2.7.4.jar  /app/lib/
cp /root/.m2/repository/org/glassfish/jaxb/jaxb-runtime/4.0.5/jaxb-runtime-4.0.5.jar  /app/lib/
cp /root/.m2/repository/org/glassfish/jaxb/txw2/4.0.5/txw2-4.0.5.jar  /app/lib/
cp /root/.m2/repository/org/glassfish/jaxb/jaxb-core/4.0.5/jaxb-core-4.0.5.jar  /app/lib/
cp /root/.m2/repository/org/liquibase/liquibase-maven-plugin/4.33.0/liquibase-maven-plugin-4.33.0.jar  /app/lib/
cp /root/.m2/repository/org/liquibase/liquibase-core/4.8.0/liquibase-core-4.8.0.jar  /app/lib/
cp /root/.m2/repository/org/liquibase/liquibase-core/4.3.5/liquibase-core-4.3.5.jar  /app/lib/
cp /root/.m2/repository/org/modelmapper/modelmapper/2.3.0/modelmapper-2.3.0.jar  /app/lib/
cp /root/.m2/repository/org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar  /app/lib/
cp /root/.m2/repository/org/hibernate/validator/hibernate-validator/8.0.1.Final/hibernate-validator-8.0.1.Final.jar  /app/lib/
cp /root/.m2/repository/org/hibernate/orm/hibernate-core/6.5.3.Final/hibernate-core-6.5.3.Final.jar  /app/lib/
cp /root/.m2/repository/org/hibernate/common/hibernate-commons-annotations/6.0.6.Final/hibernate-commons-annotations-6.0.6.Final.jar  /app/lib/
cp /root/.m2/repository/org/gagravarr/vorbis-java-tika/0.8/vorbis-java-tika-0.8.jar  /app/lib/
cp /root/.m2/repository/org/gagravarr/vorbis-java-core/0.8/vorbis-java-core-0.8.jar  /app/lib/
cp /root/.m2/repository/org/ow2/asm/asm-analysis/9.7/asm-analysis-9.7.jar  /app/lib/
cp /root/.m2/repository/org/ow2/asm/asm/9.3/asm-9.3.jar  /app/lib/
cp /root/.m2/repository/org/ow2/asm/asm/9.6/asm-9.6.jar  /app/lib/
cp /root/.m2/repository/org/ow2/asm/asm/9.7/asm-9.7.jar  /app/lib/
cp /root/.m2/repository/org/ow2/asm/asm/9.4/asm-9.4.jar  /app/lib/
cp /root/.m2/repository/org/ow2/asm/asm/7.2/asm-7.2.jar  /app/lib/
cp /root/.m2/repository/org/ow2/asm/asm-util/9.7/asm-util-9.7.jar  /app/lib/
cp /root/.m2/repository/org/ow2/asm/asm-tree/9.7/asm-tree-9.7.jar  /app/lib/
cp /root/.m2/repository/org/hdrhistogram/HdrHistogram/2.2.2/HdrHistogram-2.2.2.jar  /app/lib/
cp /root/.m2/repository/org/netpreserve/jwarc/0.30.0/jwarc-0.30.0.jar  /app/lib/
cp /root/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar  /app/lib/
cp /root/.m2/repository/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar  /app/lib/
cp /root/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar  /app/lib/
cp /root/.m2/repository/org/awaitility/awaitility/4.2.2/awaitility-4.2.2.jar  /app/lib/
cp /root/.m2/repository/org/junit/platform/junit-platform-commons/1.10.5/junit-platform-commons-1.10.5.jar  /app/lib/
cp /root/.m2/repository/org/junit/platform/junit-platform-launcher/1.10.5/junit-platform-launcher-1.10.5.jar  /app/lib/
cp /root/.m2/repository/org/junit/platform/junit-platform-engine/1.10.5/junit-platform-engine-1.10.5.jar  /app/lib/
cp /root/.m2/repository/org/junit/jupiter/junit-jupiter/5.10.5/junit-jupiter-5.10.5.jar  /app/lib/
cp /root/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.7.1/junit-jupiter-engine-5.7.1.jar  /app/lib/
cp /root/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.10.5/junit-jupiter-engine-5.10.5.jar  /app/lib/
cp /root/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.10.5/junit-jupiter-params-5.10.5.jar  /app/lib/
cp /root/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.7.1/junit-jupiter-api-5.7.1.jar  /app/lib/
cp /root/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.10.5/junit-jupiter-api-5.10.5.jar  /app/lib/
cp /root/.m2/repository/org/slf4j/slf4j-api/2.0.16/slf4j-api-2.0.16.jar  /app/lib/
cp /root/.m2/repository/org/slf4j/jcl-over-slf4j/2.0.16/jcl-over-slf4j-2.0.16.jar  /app/lib/
cp /root/.m2/repository/org/slf4j/jul-to-slf4j/2.0.16/jul-to-slf4j-2.0.16.jar  /app/lib/
cp /root/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar  /app/lib/
cp /root/.m2/repository/org/checkerframework/checker-qual/3.47.0/checker-qual-3.47.0.jar  /app/lib/
cp /root/.m2/repository/org/checkerframework/checker-qual/3.42.0/checker-qual-3.42.0.jar  /app/lib/
cp /root/.m2/repository/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.jar  /app/lib/
cp /root/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar  /app/lib/
cp /root/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar  /app/lib/
cp /root/.m2/repository/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar  /app/lib/
cp /root/.m2/repository/org/brotli/dec/0.1.2/dec-0.1.2.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/woodstox/stax2-api/4.2.2/stax2-api-4.2.2.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-io/3.2.0/plexus-io-3.2.0.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-io/3.4.1/plexus-io-3.4.1.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-io/3.4.0/plexus-io-3.4.0.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.2.3/plexus-classworlds-2.2.3.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-compiler-manager/2.13.0/plexus-compiler-manager-2.13.0.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.13.0/plexus-compiler-api-2.13.0.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-archiver/4.2.1/plexus-archiver-4.2.1.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-archiver/4.4.0/plexus-archiver-4.4.0.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-archiver/4.7.1/plexus-archiver-4.7.1.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.26/plexus-interpolation-1.26.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-compiler-javac/2.13.0/plexus-compiler-javac-2.13.0.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-utils/3.5.0/plexus-utils-3.5.0.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-utils/3.4.2/plexus-utils-3.4.2.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-utils/3.5.1/plexus-utils-3.5.1.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-java/1.1.2/plexus-java-1.1.2.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-java/1.2.0/plexus-java-1.2.0.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-java/1.0.5/plexus-java-1.0.5.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar  /app/lib/
cp /root/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.24/animal-sniffer-annotations-1.24.jar  /app/lib/
cp /root/.m2/repository/org/testng/testng/7.9.0/testng-7.9.0.jar  /app/lib/
cp /root/.m2/repository/org/webjars/webjars-locator-core/0.58/webjars-locator-core-0.58.jar  /app/lib/
cp /root/.m2/repository/org/webjars/jquery/3.7.1/jquery-3.7.1.jar  /app/lib/
cp /root/.m2/repository/org/webjars/swagger-ui/4.5.0/swagger-ui-4.5.0.jar  /app/lib/
cp /root/.m2/repository/org/postgresql/postgresql/42.6.1/postgresql-42.6.1.jar  /app/lib/
cp /root/.m2/repository/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.jar  /app/lib/
cp /root/.m2/repository/org/hamcrest/hamcrest-core/2.2/hamcrest-core-2.2.jar  /app/lib/
cp /root/.m2/repository/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar  /app/lib/
cp /root/.m2/repository/org/aspectj/aspectjweaver/1.9.22.1/aspectjweaver-1.9.22.1.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-expression/6.0.8/spring-expression-6.0.8.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-expression/6.1.14/spring-expression-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-test/6.1.14/spring-test-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-webflux/6.1.14/spring-webflux-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.3.5/spring-boot-starter-logging-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-test/3.3.5/spring-boot-starter-test-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/3.3.5/spring-boot-actuator-autoconfigure-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/3.0.6/spring-boot-actuator-autoconfigure-3.0.6.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-security/3.3.5/spring-boot-starter-security-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter/3.4.0/spring-boot-starter-3.4.0.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-validation/3.3.5/spring-boot-starter-validation-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-mail/3.3.5/spring-boot-starter-mail-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-oauth2-resource-server/3.3.5/spring-boot-starter-oauth2-resource-server-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot/3.3.5/spring-boot-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-webflux/3.3.5/spring-boot-starter-webflux-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/3.3.5/spring-boot-starter-jdbc-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-aop/3.3.5/spring-boot-starter-aop-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-quartz/3.3.5/spring-boot-starter-quartz-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.1.6/spring-boot-starter-web-3.1.6.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.3.5/spring-boot-starter-web-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-data-jpa/3.2.1/spring-boot-starter-data-jpa-3.2.1.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-data-jpa/3.3.5/spring-boot-starter-data-jpa-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-test/3.3.5/spring-boot-test-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/3.3.5/spring-boot-starter-actuator-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.3.5/spring-boot-starter-json-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-reactor-netty/3.3.5/spring-boot-starter-reactor-netty-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-actuator/3.3.5/spring-boot-actuator-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.3.5/spring-boot-starter-tomcat-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-starter-web-services/3.3.5/spring-boot-starter-web-services-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.3.5/spring-boot-autoconfigure-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.0.7/spring-boot-autoconfigure-3.0.7.jar  /app/lib/
cp /root/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/3.3.5/spring-boot-test-autoconfigure-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-orm/6.1.14/spring-orm-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-aop/6.1.14/spring-aop-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-context/6.1.14/spring-context-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-mock/2.0.4/spring-mock-2.0.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/vault/spring-vault-core/3.1.1/spring-vault-core-3.1.1.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-jdbc/6.1.14/spring-jdbc-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/cloud/spring-cloud-starter-vault-config/4.1.3/spring-cloud-starter-vault-config-4.1.3.jar  /app/lib/
cp /root/.m2/repository/org/springframework/cloud/spring-cloud-vault-config/4.1.3/spring-cloud-vault-config-4.1.3.jar  /app/lib/
cp /root/.m2/repository/org/springframework/cloud/spring-cloud-starter/4.1.3/spring-cloud-starter-4.1.3.jar  /app/lib/
cp /root/.m2/repository/org/springframework/cloud/spring-cloud-context/4.1.3/spring-cloud-context-4.1.3.jar  /app/lib/
cp /root/.m2/repository/org/springframework/cloud/spring-cloud-commons/4.1.3/spring-cloud-commons-4.1.3.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-aspects/6.1.14/spring-aspects-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-oxm/6.1.14/spring-oxm-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-jcl/6.1.14/spring-jcl-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-core/6.1.14/spring-core-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-core/6.0.0/spring-core-6.0.0.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-messaging/6.1.14/spring-messaging-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-web/6.1.4/spring-web-6.1.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-web/6.1.14/spring-web-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-webmvc/6.1.14/spring-webmvc-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-webmvc/6.0.14/spring-webmvc-6.0.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/data/spring-data-jpa/3.2.1/spring-data-jpa-3.2.1.jar  /app/lib/
cp /root/.m2/repository/org/springframework/data/spring-data-jpa/3.3.5/spring-data-jpa-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/data/spring-data-commons/3.2.1/spring-data-commons-3.2.1.jar  /app/lib/
cp /root/.m2/repository/org/springframework/data/spring-data-commons/3.3.5/spring-data-commons-3.3.5.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-beans/6.1.14/spring-beans-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-context-support/6.1.14/spring-context-support-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-websocket/6.1.14/spring-websocket-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/spring-tx/6.1.14/spring-tx-6.1.14.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-data/6.3.4/spring-security-data-6.3.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-oauth2-jose/6.4.3/spring-security-oauth2-jose-6.4.3.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-oauth2-jose/6.2.4/spring-security-oauth2-jose-6.2.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-crypto/6.3.4/spring-security-crypto-6.3.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-config/6.1.2/spring-security-config-6.1.2.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-config/6.3.4/spring-security-config-6.3.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-web/6.3.4/spring-security-web-6.3.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-core/6.3.4/spring-security-core-6.3.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-core/6.0.3/spring-security-core-6.0.3.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-oauth2-resource-server/6.3.4/spring-security-oauth2-resource-server-6.3.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-oauth2-core/6.3.4/spring-security-oauth2-core-6.3.4.jar  /app/lib/
cp /root/.m2/repository/org/springframework/security/spring-security-rsa/1.1.2/spring-security-rsa-1.1.2.jar  /app/lib/
cp /root/.m2/repository/org/springframework/ws/spring-ws-core/4.0.11/spring-ws-core-4.0.11.jar  /app/lib/
cp /root/.m2/repository/org/springframework/ws/spring-xml/4.0.11/spring-xml-4.0.11.jar  /app/lib/
cp /root/.m2/repository/org/jsoup/jsoup/1.15.3/jsoup-1.15.3.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.jar  /app/lib/
cp /root/.m2/repository/org/sonatype/aether/aether-api/1.7/aether-api-1.7.jar  /app/lib/
cp /root/.m2/repository/org/springdoc/springdoc-openapi-ui/1.6.6/springdoc-openapi-ui-1.6.6.jar  /app/lib/
cp /root/.m2/repository/org/springdoc/springdoc-openapi-webmvc-core/1.6.6/springdoc-openapi-webmvc-core-1.6.6.jar  /app/lib/
cp /root/.m2/repository/org/springdoc/springdoc-openapi-common/1.6.6/springdoc-openapi-common-1.6.6.jar  /app/lib/
cp /root/.m2/repository/org/apache/logging/log4j/log4j-core/2.23.1/log4j-core-2.23.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/logging/log4j/log4j-api/2.23.1/log4j-api-2.23.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.23.1/log4j-to-slf4j-2.23.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/pdfbox-tools/3.0.2/pdfbox-tools-3.0.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/jbig2-imageio/3.0.4/jbig2-imageio-3.0.4.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/pdfbox/3.0.2/pdfbox-3.0.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/pdfbox/3.0.3/pdfbox-3.0.3.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/jempbox/1.8.17/jempbox-1.8.17.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/xmpbox/3.0.2/xmpbox-3.0.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/fontbox/3.0.2/fontbox-3.0.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/fontbox/3.0.3/fontbox-3.0.3.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/pdfbox-io/3.0.2/pdfbox-io-3.0.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/pdfbox/pdfbox-io/3.0.3/pdfbox-io-3.0.3.jar  /app/lib/
cp /root/.m2/repository/org/apache/james/apache-mime4j-dom/0.8.11/apache-mime4j-dom-0.8.11.jar  /app/lib/
cp /root/.m2/repository/org/apache/james/apache-mime4j-core/0.8.11/apache-mime4j-core-0.8.11.jar  /app/lib/
cp /root/.m2/repository/org/apache/james/apache-mime4j-core/0.8.10/apache-mime4j-core-0.8.10.jar  /app/lib/
cp /root/.m2/repository/org/apache/tomcat/tomcat-annotations-api/10.1.31/tomcat-annotations-api-10.1.31.jar  /app/lib/
cp /root/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/10.1.31/tomcat-embed-websocket-10.1.31.jar  /app/lib/
cp /root/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.1.31/tomcat-embed-el-10.1.31.jar  /app/lib/
cp /root/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/10.1.34/tomcat-embed-core-10.1.34.jar  /app/lib/
cp /root/.m2/repository/org/apache/poi/poi-scratchpad/5.3.0/poi-scratchpad-5.3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/poi/poi-ooxml-lite/5.2.2/poi-ooxml-lite-5.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/poi/poi/5.2.3/poi-5.2.3.jar  /app/lib/
cp /root/.m2/repository/org/apache/poi/poi/5.2.2/poi-5.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/poi/poi-ooxml/5.2.2/poi-ooxml-5.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/xmlbeans/xmlbeans/5.0.3/xmlbeans-5.0.3.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-code-module/3.0.0-BETA2/tika-parser-code-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-text-module/3.0.0-BETA2/tika-parser-text-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-cad-module/3.0.0-BETA2/tika-parser-cad-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-core/3.0.0-BETA2/tika-core-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-font-module/3.0.0-BETA2/tika-parser-font-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-audiovideo-module/3.0.0-BETA2/tika-parser-audiovideo-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-ocr-module/3.0.0-BETA2/tika-parser-ocr-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-pdf-module/3.0.0-BETA2/tika-parser-pdf-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-mail-commons/3.0.0-BETA2/tika-parser-mail-commons-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-microsoft-module/3.0.0-BETA2/tika-parser-microsoft-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-news-module/3.0.0-BETA2/tika-parser-news-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-webarchive-module/3.0.0-BETA2/tika-parser-webarchive-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-crypto-module/3.0.0-BETA2/tika-parser-crypto-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-zip-commons/3.0.0-BETA2/tika-parser-zip-commons-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-xmp-commons/3.0.0-BETA2/tika-parser-xmp-commons-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parsers-standard-package/3.0.0-BETA2/tika-parsers-standard-package-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-miscoffice-module/3.0.0-BETA2/tika-parser-miscoffice-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-digest-commons/3.0.0-BETA2/tika-parser-digest-commons-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-xml-module/3.0.0-BETA2/tika-parser-xml-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-html-module/3.0.0-BETA2/tika-parser-html-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-apple-module/3.0.0-BETA2/tika-parser-apple-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-mail-module/3.0.0-BETA2/tika-parser-mail-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-pkg-module/3.0.0-BETA2/tika-parser-pkg-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/tika/tika-parser-image-module/3.0.0-BETA2/tika-parser-image-module-3.0.0-BETA2.jar  /app/lib/
cp /root/.m2/repository/org/apache/ivy/ivy/2.5.2/ivy-2.5.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-csv/1.11.0/commons-csv-1.11.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-exec/1.4.0/commons-exec-1.4.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-compress/1.23.0/commons-compress-1.23.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-compress/1.26.1/commons-compress-1.26.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-compress/1.19/commons-compress-1.19.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-text/1.10.0/commons-text-1.10.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/ant/ant-junit/1.10.15/ant-junit-1.10.15.jar  /app/lib/
cp /root/.m2/repository/org/apache/ant/ant-antlr/1.10.15/ant-antlr-1.10.15.jar  /app/lib/
cp /root/.m2/repository/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.jar  /app/lib/
cp /root/.m2/repository/org/apache/ant/ant/1.10.15/ant-1.10.15.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-jmx/4.0.23/groovy-jmx-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-datetime/4.0.23/groovy-datetime-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-servlet/4.0.23/groovy-servlet-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-templates/4.0.23/groovy-templates-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-jsr223/4.0.23/groovy-jsr223-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-swing/4.0.23/groovy-swing-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-yaml/4.0.23/groovy-yaml-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-xml/4.0.23/groovy-xml-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-test/4.0.23/groovy-test-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-json/4.0.23/groovy-json-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-groovydoc/4.0.23/groovy-groovydoc-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy/4.0.23/groovy-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-cli-picocli/4.0.23/groovy-cli-picocli-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-test-junit5/4.0.23/groovy-test-junit5-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-docgenerator/4.0.23/groovy-docgenerator-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-ant/4.0.23/groovy-ant-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-console/4.0.23/groovy-console-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-groovysh/4.0.23/groovy-groovysh-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-sql/4.0.23/groovy-sql-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-macro/4.0.23/groovy-macro-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/groovy/groovy-nio/4.0.23/groovy-nio-4.0.23.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.10/wagon-provider-api-2.10.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-api/3.0.0-M5/surefire-api-3.0.0-M5.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-api/3.2.2/surefire-api-3.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-shared-utils/3.0.0-M4/surefire-shared-utils-3.0.0-M4.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-shared-utils/3.2.2/surefire-shared-utils-3.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-extensions-spi/3.0.0-M5/surefire-extensions-spi-3.0.0-M5.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-extensions-spi/3.2.2/surefire-extensions-spi-3.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-extensions-api/3.0.0-M5/surefire-extensions-api-3.0.0-M5.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-extensions-api/3.2.2/surefire-extensions-api-3.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-logger-api/3.0.0-M5/surefire-logger-api-3.0.0-M5.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-logger-api/3.2.2/surefire-logger-api-3.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-booter/3.0.0-M5/surefire-booter-3.0.0-M5.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/surefire-booter/3.2.2/surefire-booter-3.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/maven-surefire-common/3.0.0-M5/maven-surefire-common-3.0.0-M5.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/surefire/maven-surefire-common/3.2.2/maven-surefire-common-3.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-plugin-api/3.0/maven-plugin-api-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-settings-builder/3.0/maven-settings-builder-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-toolchain/3.0-alpha-2/maven-toolchain-3.0-alpha-2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-repository-metadata/3.0/maven-repository-metadata-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-archiver/3.5.0/maven-archiver-3.5.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-archiver/3.6.0/maven-archiver-3.6.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/file-management/3.1.0/file-management-3.1.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/file-management/3.0.0/file-management-3.0.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/maven-filtering/3.3.1/maven-filtering-3.3.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/maven-shared-io/3.0.0/maven-shared-io-3.0.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.3.2/maven-common-artifact-filters-3.3.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.1.0/maven-common-artifact-filters-3.1.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.1.1/maven-common-artifact-filters-3.1.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.11.0/maven-artifact-transfer-0.11.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-compat/3.0/maven-compat-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin/3.0.0-M5/maven-surefire-plugin-3.0.0-M5.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin/3.2.2/maven-surefire-plugin-3.2.2.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/plugins/maven-clean-plugin/3.2.0/maven-clean-plugin-3.2.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/plugins/maven-compiler-plugin/3.11.0/maven-compiler-plugin-3.11.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/plugins/maven-resources-plugin/3.3.1/maven-resources-plugin-3.3.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/plugins/maven-jar-plugin/3.2.0/maven-jar-plugin-3.2.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/plugins/maven-jar-plugin/3.3.0/maven-jar-plugin-3.3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/plugins/maven-install-plugin/3.1.1/maven-install-plugin-3.1.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/plugins/maven-assembly-plugin/3.6.0/maven-assembly-plugin-3.6.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-artifact/3.0/maven-artifact-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-model-builder/3.0/maven-model-builder-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-aether-provider/3.0/maven-aether-provider-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-core/3.0/maven-core-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-model/3.0/maven-model-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/maven/maven-settings/3.0/maven-settings-3.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/qpid/proton-j/0.34.1/proton-j-0.34.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/lucene/lucene-sandbox/8.10.0/lucene-sandbox-8.10.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/lucene/lucene-sandbox/8.11.1/lucene-sandbox-8.11.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/lucene/lucene-queries/8.10.0/lucene-queries-8.10.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/lucene/lucene-queries/8.11.1/lucene-queries-8.11.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/lucene/lucene-analyzers-common/8.9.0/lucene-analyzers-common-8.9.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/lucene/lucene-queryparser/8.10.0/lucene-queryparser-8.10.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/lucene/lucene-queryparser/8.11.1/lucene-queryparser-8.11.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/lucene/lucene-core/8.9.0/lucene-core-8.9.0.jar  /app/lib/
cp /root/.m2/repository/org/apache/lucene/lucene-core/8.11.1/lucene-core-8.11.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar  /app/lib/
cp /root/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar  /app/lib/
cp /root/.m2/repository/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar  /app/lib/
cp /root/.m2/repository/org/apache/httpcomponents/client5/httpclient5/5.2.1/httpclient5-5.2.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/httpcomponents/client5/httpclient5/5.3.1/httpclient5-5.3.1.jar  /app/lib/
cp /root/.m2/repository/org/apache/httpcomponents/httpmime/4.5.14/httpmime-4.5.14.jar  /app/lib/
cp /root/.m2/repository/org/apache/httpcomponents/core5/httpcore5/5.2.5/httpcore5-5.2.5.jar  /app/lib/
cp /root/.m2/repository/org/apache/httpcomponents/core5/httpcore5-h2/5.2.5/httpcore5-h2-5.2.5.jar  /app/lib/
cp /root/.m2/repository/org/threeten/threetenbp/1.7.0/threetenbp-1.7.0.jar  /app/lib/
cp /root/.m2/repository/org/quartz-scheduler/quartz/2.3.2/quartz-2.3.2.jar  /app/lib/
cp /root/.m2/repository/org/bouncycastle/bcpkix-jdk18on/1.78.1/bcpkix-jdk18on-1.78.1.jar  /app/lib/
cp /root/.m2/repository/org/bouncycastle/bcjmail-jdk18on/1.78.1/bcjmail-jdk18on-1.78.1.jar  /app/lib/
cp /root/.m2/repository/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1.jar  /app/lib/
cp /root/.m2/repository/org/bouncycastle/bcutil-jdk18on/1.78.1/bcutil-jdk18on-1.78.1.jar  /app/lib/
cp /root/.m2/repository/org/antlr/antlr4-runtime/4.13.0/antlr4-runtime-4.13.0.jar  /app/lib/
cp /root/.m2/repository/org/skyscreamer/jsonassert/1.5.3/jsonassert-1.5.3.jar  /app/lib/
cp /root/.m2/repository/org/yaml/snakeyaml/2.2/snakeyaml-2.2.jar  /app/lib/
cp /root/.m2/repository/org/objenesis/objenesis/3.3/objenesis-3.3.jar  /app/lib/
cp /root/.m2/repository/org/conscrypt/conscrypt-openjdk-uber/2.5.2/conscrypt-openjdk-uber-2.5.2.jar  /app/lib/
cp /root/.m2/repository/org/json/json/20240303/json-20240303.jar  /app/lib/
cp /root/.m2/repository/org/json/json/20231013/json-20231013.jar  /app/lib/
cp /root/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.9.25/kotlin-stdlib-jdk7-1.9.25.jar  /app/lib/
cp /root/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.9.25/kotlin-stdlib-jdk8-1.9.25.jar  /app/lib/
cp /root/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.9.25/kotlin-stdlib-common-1.9.25.jar  /app/lib/
cp /root/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.9.25/kotlin-stdlib-1.9.25.jar  /app/lib/
cp /root/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar  /app/lib/
cp /root/.m2/repository/org/jboss/logging/jboss-logging/3.5.3.Final/jboss-logging-3.5.3.Final.jar  /app/lib/
cp /root/.m2/repository/org/jvnet/staxex/stax-ex/2.1.0/stax-ex-2.1.0.jar  /app/lib/
cp /root/.m2/repository/org/jdom/jdom2/2.0.6.1/jdom2-2.0.6.1.jar  /app/lib/
cp /root/.m2/repository/org/ehcache/ehcache/3.9.0/ehcache-3.9.0.jar  /app/lib/
cp /root/.m2/repository/org/reactivestreams/reactive-streams/1.0.4/reactive-streams-1.0.4.jar  /app/lib/
cp /root/.m2/repository/org/assertj/assertj-core/3.25.3/assertj-core-3.25.3.jar  /app/lib/
cp /root/.m2/repository/org/tukaani/xz/1.9/xz-1.9.jar  /app/lib/
cp /root/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar  /app/lib/
cp /root/.m2/repository/org/mockito/mockito-all/2.0.2-beta/mockito-all-2.0.2-beta.jar  /app/lib/
cp /root/.m2/repository/org/mockito/mockito-junit-jupiter/5.11.0/mockito-junit-jupiter-5.11.0.jar  /app/lib/
cp /root/.m2/repository/org/mockito/mockito-core/5.11.0/mockito-core-5.11.0.jar  /app/lib/
cp /root/.m2/repository/org/eclipse/angus/jakarta.mail/2.0.3/jakarta.mail-2.0.3.jar  /app/lib/
cp /root/.m2/repository/org/eclipse/angus/angus-activation/2.0.2/angus-activation-2.0.2.jar  /app/lib/
cp /root/.m2/repository/org/eclipse/aether/aether-util/1.0.0.v20140518/aether-util-1.0.0.v20140518.jar  /app/lib/
cp /root/.m2/repository/org/eclipse/aether/aether-api/1.0.0.v20140518/aether-api-1.0.0.v20140518.jar  /app/lib/
cp /root/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/5.13.0.202109080827-r/org.eclipse.jgit-5.13.0.202109080827-r.jar  /app/lib/
cp /root/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/6.8.0.202311291450-r/org.eclipse.jgit-6.8.0.202311291450-r.jar  /app/lib/
cp /root/.m2/repository/avalon-framework/avalon-framework/4.1.3/avalon-framework-4.1.3.jar  /app/lib/
cp /root/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar  /app/lib/
cp /root/.m2/repository/commons-logging/commons-logging/1.1/commons-logging-1.1.jar  /app/lib/
cp /root/.m2/repository/commons-logging/commons-logging/1.3.3/commons-logging-1.3.3.jar  /app/lib/
cp /root/.m2/repository/dev/langchain4j/langchain4j-core/0.33.0/langchain4j-core-0.33.0.jar  /app/lib/
cp /root/.m2/repository/dev/langchain4j/langchain4j-bedrock/0.33.0/langchain4j-bedrock-0.33.0.jar  /app/lib/
cp /root/.m2/repository/dev/langchain4j/langchain4j-vertex-ai-gemini/0.35.0/langchain4j-vertex-ai-gemini-0.35.0.jar  /app/lib/
cp /root/.m2/repository/dev/langchain4j/langchain4j-azure-open-ai/0.33.0/langchain4j-azure-open-ai-0.33.0.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/sdk-core/2.20.23/sdk-core-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/sdk-core/2.20.162/sdk-core-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/aws-core/2.20.23/aws-core-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/aws-core/2.20.162/aws-core-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/profiles/2.20.23/profiles-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/profiles/2.20.162/profiles-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/cloudwatchlogs/2.20.24/cloudwatchlogs-2.20.24.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/protocol-core/2.20.23/protocol-core-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/protocol-core/2.20.162/protocol-core-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/regions/2.20.23/regions-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/regions/2.20.162/regions-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/arns/2.17.0/arns-2.17.0.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/bedrockruntime/2.20.162/bedrockruntime-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/auth/2.20.23/auth-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/auth/2.20.162/auth-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/utils/2.20.23/utils-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/utils/2.20.162/utils-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/apache-client/2.20.23/apache-client-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/apache-client/2.20.162/apache-client-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/s3/2.17.0/s3-2.17.0.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/http-client-spi/2.20.23/http-client-spi-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/http-client-spi/2.20.162/http-client-spi-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/sagemaker/2.20.23/sagemaker-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/endpoints-spi/2.20.23/endpoints-spi-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/endpoints-spi/2.20.162/endpoints-spi-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/json-utils/2.20.23/json-utils-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/json-utils/2.20.162/json-utils-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/bedrock/2.20.162/bedrock-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/aws-query-protocol/2.17.0/aws-query-protocol-2.17.0.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/aws-xml-protocol/2.17.0/aws-xml-protocol-2.17.0.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/aws-json-protocol/2.20.23/aws-json-protocol-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/aws-json-protocol/2.20.162/aws-json-protocol-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/metrics-spi/2.20.23/metrics-spi-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/metrics-spi/2.20.162/metrics-spi-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/netty-nio-client/2.20.23/netty-nio-client-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/netty-nio-client/2.20.162/netty-nio-client-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/third-party-jackson-core/2.20.23/third-party-jackson-core-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/third-party-jackson-core/2.20.162/third-party-jackson-core-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/annotations/2.20.23/annotations-2.20.23.jar  /app/lib/
cp /root/.m2/repository/software/amazon/awssdk/annotations/2.20.162/annotations-2.20.162.jar  /app/lib/
cp /root/.m2/repository/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.jar  /app/lib/
cp /root/.m2/repository/software/amazon/eventstream/eventstream/1.0.1/eventstream-1.0.1.jar  /app/lib/
cp /root/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar  /app/lib/

