# =====================================================
# ICIP Service - AI/ML Pipeline & Jobs
# =====================================================
spring:
  profiles:
    active: mysql,dbjwt

  application:
    name: icip-service

  main:
    allow-bean-definition-overriding: true

server:
  port: 8082

