apiVersion: v1
kind: Service
metadata:
  name: langflow
  namespace: essedum
  labels:
    app: langflow
spec:
  selector:
    app: langflow
  ports:
    - name: http
      port: 7860
      targetPort: 7860
  type: ClusterIP
