apiVersion: v1
kind: Service
metadata:
  name: adk-code-builder-deployer
  namespace: essedum
  labels:
    app: adk-code-builder-deployer
spec:
  selector:
    app: adk-code-builder-deployer
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
