apiVersion: v1
kind: Service
metadata:
  name: langfuse-web
  namespace: essedum
  labels:
    app: langfuse-web
spec:
  selector:
    app: langfuse-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
