apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: essedum
  labels:
    app: proxy-service
spec:
  selector:
    app: proxy-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
