/**
 * @ 2021 - 2022 Infosys Limited, Bangalore, India. All Rights Reserved.
 * Version: 1.0
 * Except for any free or open source software components embedded in this Infosys proprietary software program (Program),
 * this Program is protected by copyright laws,international treaties and  other pending or existing intellectual property
 * rights in India,the United States, and other countries.Except as expressly permitted, any unauthorized reproduction,storage,
 * transmission in any form or by any means(including without limitation electronic,mechanical, printing,photocopying,
 * recording, or otherwise), or any distribution of this program, or any portion of it,may result in severe civil and
 * criminal penalties, and will be prosecuted to the maximum extent possible under the law.
 */
package com.infosys.icets.icip.icipmodelserver.constants;

// TODO: Auto-generated Javadoc
/**
 * The Class PipelineExposeConstants.
 */
public class PipelineExposeConstants {

	/**
	 * Instantiates a new pipeline expose constants.
	 */
	private PipelineExposeConstants() {
	}

	/** The Constant DEFAULT_EVENT_STRING. */
	public static final String DEFAULT_EVENT_STRING = "_AutoGenerated";

	/** The Constant CORRELATIONFILEDIRECTORY. */
	public static final String CORRELATIONFILEDIRECTORY = "correlationfiles/";

	/** The Constant CORRELATIONOUTEXTENSION. */
	public static final String CORRELATIONOUTEXTENSION = "_out.json";

	/** The Constant MODELDIRECTORY. */
	public static final String MODELDIRECTORY = "models/";
	
	/** The Constant BOOTSTRAPCALL. */
	public static final String BOOTSTRAPCALL = String.format("%s%s", MODELDIRECTORY, "bootstrap");

	/** The Constant FILENAME. */
	public static final String FILENAME = "filename";

	/** The Constant MODELSERVERERROR. */
	public static final String MODELSERVERERROR = "ModelServer executor is disabled";
	
	public static final String IS_REMOTE_DS = "isRemoteDS";
	public static final String EXECUTION_ENVIRONMENT = "executionEnvironment";
	public static final String REMOTE = "REMOTE";
	public static final String REST = "REST";
}
