/**
 * The MIT License (MIT)
 * Copyright © 2025 Infosys Limited
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.infosys.icets.icip.icipmodelserver.constants;

// TODO: Auto-generated Javadoc
/**
 * The Class PipelineExposeConstants.
 */
public class PipelineExposeConstants {

	/**
	 * Instantiates a new pipeline expose constants.
	 */
	private PipelineExposeConstants() {
	}

	/** The Constant DEFAULT_EVENT_STRING. */
	public static final String DEFAULT_EVENT_STRING = "_AutoGenerated";

	/** The Constant CORRELATIONFILEDIRECTORY. */
	public static final String CORRELATIONFILEDIRECTORY = "correlationfiles/";

	/** The Constant CORRELATIONOUTEXTENSION. */
	public static final String CORRELATIONOUTEXTENSION = "_out.json";

	/** The Constant MODELDIRECTORY. */
	public static final String MODELDIRECTORY = "models/";
	
	/** The Constant BOOTSTRAPCALL. */
	public static final String BOOTSTRAPCALL = String.format("%s%s", MODELDIRECTORY, "bootstrap");

	/** The Constant FILENAME. */
	public static final String FILENAME = "filename";

	/** The Constant MODELSERVERERROR. */
	public static final String MODELSERVERERROR = "ModelServer executor is disabled";
	
	public static final String IS_REMOTE_DS = "isRemoteDS";
	public static final String EXECUTION_ENVIRONMENT = "executionEnvironment";
	public static final String REMOTE = "REMOTE";
	public static final String REST = "REST";
}
